---
title: "Codebook for Getting Data Assignment"
author: "Tony Wilson"
date: "22 May 2015"
---
>Some parts of the text of this codebook are taken from both the assignment instructions and the readme files that accompanied the data.

## Project Description
This project was carried out as part of the programming assignment for the Getting and Cleaning Data course.  The purpose of the project is to demonstrate the ability to collect, work with and clean a data set. The goal is to produce a tidy dataset that can be used for later analysis. 


## Background
(From the course assignment)

>One of the most exciting areas in all of data science right now is wearable computing - see for example [this article](http://www.insideactivitytracking.com/data-science-activity-tracking-and-the-battle-for-the-worlds-top-sports-brand/). Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained: 

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 


##Study design and data processing

###Collection of the raw data
The experiments were carried out using a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) whilst wearing a smartphone (Samsung Galaxy S II) on the waist. Using the Samsung's embedded accelerometer and gyroscope, 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz were captured. The experiments were video-recorded to label the data manually. The obtained dataset was randomly partitioned into two sets, where 70% of the volunteers were selected for generating the training data and 30% the test data. 

###Notes on the original (raw) data 
>"The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See the '[features_info.txt](https://github.com/wilsonae/GetData_Assignment/blob/master/features_info.txt)' for more details."

###Assumptions
It is assumed that
- the raw data has been downloaded from  https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip
- the raw data has been unzipped to your working directory.  This will create a subfolder called *"UCI HAR Dataset"* in your working directory.
- [*run_analysis.R*](https://github.com/wilsonae/GetData_Assignment/blob/master/run_analysis.R) has been copied from this repo to your working directory.  (Note: **do not** copy it to the *"UCI HAR Dataset"* subfolder underneath your working directory.)
- the R packages *"dplyr"* and *"tidyr"* have already been installed.

###Creating the tidy data file

- execute the program *run_analysis.R* by typing *source("run-analysis.R")*
- on completion, a file, *feature_means.txt*, that contains the tidy dataset will be written to the *"UCI HAR Dataset"* subfolder under your working directory.  This file will have 2,310 rows and four columns.  Each observation in this file will have four variables (activity, subject, feature, mean) which are described below.

The tidy dataset should be read into R using the *read.table* command.

###Cleaning of the data
The raw data consisted of two sets of data.  The test data was held in three files and had 2,947 observations with 561 variables.  The training data was also in three files aand had 7,352 observations and 561 variables.  As the requirement was to use only the mean and standard deviation observations from the original data, the 561 variables were reduced to 66 variables. 

A complete description of how the cleaning and processing is carried out is in the [README.md](https://github.com/wilsonae/GetData_Assignment/blob/master/README.md) file.

##Description of the variables in the feature file
The tidy dataset, *feature_means.txt*, consists of 2,310 observations and four variables

Each observation consists of four pieces of data as described below.

| Variable | Name  | Type | Valid values | Description |
| :------: |:-----:|:----:| :------------| :-----------|
| 1 | activity | Factor w/ 6 levels | WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING | This is the activity that was being performed. |
| 2 | subject |   int | in the range 1:30 | ID number of the subject |
| 3 | feature | Factor w/ 66 levels | See the list below |One of the 66 features being examined |
| 4 | mean | num | -1 <= x <= 1 | The mean of all observations for this activity, subject and feature |

###Variable 1 (activity)
The **activity** variable indicates what 'exercise' was being carried out by the subject when the measurements were being taken.

The activity variable 
- is a Factor with 6 levels
- can be any one of WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING
- does not have a unit of measurement

###Variable 2 (subject)
The **subject** variable indicates the ID of the subject that was carrying out the activity for this observation.

The subject variable 
- is an int
- can be any integer between 1 and 30
- does not have a unit of measurement

###Variable 3 (feature)
The **feature** variable indicates what measurement was averaged for this actiity and subject. 

The feature variable 
- is a Factor with 66 levels
- can be any one of the 66 values in the table below
- does not have a unit of measurement

####Valid values for the feature variable
```
 [1] tBodyAcc-mean()-X           tBodyAcc-mean()-Y           tBodyAcc-mean()-Z           tBodyAcc-std()-X           
 [5] tBodyAcc-std()-Y            tBodyAcc-std()-Z            tGravityAcc-mean()-X        tGravityAcc-mean()-Y       
 [9] tGravityAcc-mean()-Z        tGravityAcc-std()-X         tGravityAcc-std()-Y         tGravityAcc-std()-Z        
[13] tBodyAccJerk-mean()-X       tBodyAccJerk-mean()-Y       tBodyAccJerk-mean()-Z       tBodyAccJerk-std()-X       
[17] tBodyAccJerk-std()-Y        tBodyAccJerk-std()-Z        tBodyGyro-mean()-X          tBodyGyro-mean()-Y         
[21] tBodyGyro-mean()-Z          tBodyGyro-std()-X           tBodyGyro-std()-Y           tBodyGyro-std()-Z          
[25] tBodyGyroJerk-mean()-X      tBodyGyroJerk-mean()-Y      tBodyGyroJerk-mean()-Z      tBodyGyroJerk-std()-X      
[29] tBodyGyroJerk-std()-Y       tBodyGyroJerk-std()-Z       tBodyAccMag-mean()          tBodyAccMag-std()          
[33] tGravityAccMag-mean()       tGravityAccMag-std()        tBodyAccJerkMag-mean()      tBodyAccJerkMag-std()      
[37] tBodyGyroMag-mean()         tBodyGyroMag-std()          tBodyGyroJerkMag-mean()     tBodyGyroJerkMag-std()     
[41] fBodyAcc-mean()-X           fBodyAcc-mean()-Y           fBodyAcc-mean()-Z           fBodyAcc-std()-X           
[45] fBodyAcc-std()-Y            fBodyAcc-std()-Z            fBodyAccJerk-mean()-X       fBodyAccJerk-mean()-Y      
[49] fBodyAccJerk-mean()-Z       fBodyAccJerk-std()-X        fBodyAccJerk-std()-Y        fBodyAccJerk-std()-Z       
[53] fBodyGyro-mean()-X          fBodyGyro-mean()-Y          fBodyGyro-mean()-Z          fBodyGyro-std()-X          
[57] fBodyGyro-std()-Y           fBodyGyro-std()-Z           fBodyAccMag-mean()          fBodyAccMag-std()          
[61] fBodyBodyAccJerkMag-mean()  fBodyBodyAccJerkMag-std()   fBodyBodyGyroMag-mean()     fBodyBodyGyroMag-std()     
[65] fBodyBodyGyroJerkMag-mean() fBodyBodyGyroJerkMag-std() 
```

####Notes on variable 3:
Complete details of the meaning of these variable names are given in the [features_info.txt](https://github.com/wilsonae/GetData_Assignment/blob/master/features_info.txt) file that is both in this repo and in the "UCI HAR Dataset" folder under your working directory.

###Variable 4 (mean)
The **mean** variable is the calculated mean of all the original observations for the current activity, subject and feature.

The mean variable 
- is a num
- can take any real number, x, in the range -1 <= x <= 1
- has a unit of measurement dependent upon the corresponding feature
  - if the feature contains the string "Acc", the unit of measurement is *metres per second per second*
  - if the feature contains the string "Gyro", the unit of measurement is *radians per second*.

##R Packages Used
In addition to the basic installation of R, this program uses the R packages *"dplyr"* and *"tidyr"*.

